name: cuidapet_mobile
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  asuka: ^2.2.0
  dio: ^5.4.0
  firebase_analytics: ^10.7.2
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  firebase_remote_config: ^4.3.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^6.0.3
  flutter_mobx: ^2.2.0
  flutter_modular: 5.0.3
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_typeahead: ^5.0.1
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  google_places_rest_api:
    path: packages/google_places_rest_api/
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  logger: ^2.0.2+1
  mobx: ^2.2.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  synchronized: ^3.1.0
  url_launcher: ^6.2.1
  validatorless: ^1.2.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: CuidapetIcons
      fonts:
        - asset: assets/fonts/CuidapetIcons.ttf
